id,name,isactive,isstandard,number_of_providers_included__c,number_of_prt_included__c
01s0Z000004H4oJQAS,1.2 SR Engage - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H6hbQAC,1.2 SR Engagement Plus - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5QEQA0,"1.21 SR Engagement Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H5Y8QAK,"1.22 SR Engagement Suite - annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6hWQAS,"1.23 SR Engagement Plus Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6hRQAS,"1.24 SR Engagement Plus Suite - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4oOQAS,1.3 SR Marketing - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5TcQAK,"1.31 SR Marketing Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H5YcQAK,"1.32 SR Marketing Suite - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4oFQAS,1.4 PRM Suite - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5UQQA0,"1.41 Full PRM Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H5YmQAK,"1.42 Full PRM Suite - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4qjQAC,2.2 SR Engage - Satellite - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5QJQA0,"2.21 Satellite - SR Engagement Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6RoQAK,"2.22 Satellite - SR Engagement Suite - annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4qoQAC,2.3 SR Marketing - Satellite - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5TrQAK,"2.31 Satellite - SR Marketing Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6RtQAK,"2.32 Satellite - SR Marketing Suite - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4qtQAC,2.4 PRM Suite - Satellite - Advance Billing,TRUE,FALSE,5,3
01s0Z000004H5UVQA0,"2.41 Satellite - Full PRM Suite - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6RyQAK,"2.42 Satellite  - Full PRM Suite - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H5DEQA0,3.2 SR Engage - Month-to-Month,TRUE,FALSE,5,3
01s0Z000004H5DJQA0,3.3 SR Marketing - Month-to-Month,TRUE,FALSE,5,3
01s0Z000004H57kQAC,3.4 PRM Suite - Month-to-Month,TRUE,FALSE,5,3
01s0Z000004H4qyQAC,5. Partner - AGD - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5I5QAK,5. Partner - Comfort Dental - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IAQA0,5. Partner - Dental Cooperative - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IZQA0,5. Partner - IDOC - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IeQAK,5. Partner - IECP - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IPQA0,5. Partner - LDA - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IUQA0,5. Partner - MPPG - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IoQAK,5. Partner - PVG - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IFQA0,5. Partner - Smile Source - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H4r3QAC,5. Partner - Vision Source - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H6MtQAK,"5. Partner - Vision Source - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H5IKQA0,5. Partner - Vision Trends - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IjQAK,5. Partner - Vision West - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5ItQAK,5. Partner - VSP - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H5IyQAK,5. Partner - Williams Group - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H6FiQAK,"5. Partner - Williams Group - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H5J3QAK,5. Partner - WVA - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H6EuQAK,"5.2 Partner - AGD - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6EzQAK,"5.2 Partner - Comfort Dental - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6F4QAK,"5.2 Partner - Dental Cooperative - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FxQAK,"5.2 Partner - IDOC - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6F9QAK,"5.2 Partner - IECP - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FEQA0,"5.2 Partner - LDA - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FJQA0,"5.2 Partner - PVG - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FOQA0,"5.2 Partner - SmileSource - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FsQAK,"5.2 Partner - Vision Source - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FTQA0,"5.2 Partner - Vision Trends - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FYQA0,"5.2 Partner - Vision West - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FdQAK,"5.2 Partner - VSP - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6FnQAK,"5.2 Partner - WVA - Advance Billing - 12 mo contract, paid mo, no sat",TRUE,FALSE,5,3
01s0Z000004H6NSQA0,"5.42 Partner - AGD - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NhQAK,"5.42 Partner - Comfort Dental - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NNQA0,"5.42 Partner - Dental Cooperative - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6O1QAK,"5.42 Partner - IDOC - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NXQA0,"5.42 Partner - IECP - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NmQAK,"5.42 Partner - LDA - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NIQA0,"5.42 Partner - PVG - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NDQA0,"5.42 Partner - Smile Source - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6N3QAK,"5.42 Partner - Vision Source - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6N8QAK,"5.42 Partner - Vision Trends - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NcQAK,"5.42 Partner - Vision West - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NrQAK,"5.42 Partner - VSP - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6O6QAK,"5.42 Partner - Williams Group - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H6NwQAK,"5.42 Partner - WVA - Annual contract, no sat",TRUE,FALSE,5,3
01s0Z000004H4spQAC,8. Add Product - Advanced Billing,TRUE,FALSE,3,3
01s0Z000004H4uHQAS,8. Add Product - CE - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H4uMQAS,8. Add Product - ICU - Advance Billing,TRUE,FALSE,3,3
01s0Z000004H4uWQAS,8. Add Product - PCU - Advance Billing,TRUE,FALSE,3,3
01si00000048VpoAAE,Healthgrades 1,TRUE,FALSE,,
01si00000048VptAAE,Healthgrades 2,TRUE,FALSE,,
01si00000048VpyAAE,Healthgrades 3,TRUE,FALSE,,
01si0000001UiumAAC,Standard Price Book,TRUE,TRUE,,
