Name,Id,Value__c,Description__c
TaskHistoryDeleteDays,a140Z000005z9lSQAQ,150,TaskHistoryDeleteDays
New Customer Contract Email Template,a140Z000005khlHQAQ,00X0Z000001FzXh,New Customer Contract Email Template
Campaign Influence Orphan Days,a14310000053bcyAAA,29,Campaign Influence will automatically change to Orphaned after this many days without an ROE activity
Opportunity Closed Lost Days,a14310000053bctAAA,29,Opportunities will automatically change to Closed Lost after this many days without an ROE activity
Powerstone Distribution Group,a140Z0000060R1qQAE,a3O31000000DWaz,Powerstone Distribution Group
Contract Email Template No Sub ID,a140Z000005kuLPQAY,00X0Z000001G0Tq,Contract Email Template No Sub ID
SRSR Onboarding Queue,a140Z000005nTomQAE,00G31000004at3x,ID for SRSR Onboarding Queue
SRC Onboarding Queue,a140Z000005nTocQAE,00G31000004at3x,ID for SRC Onboarding Queue
SRS Onboarding Queue,a140Z000005nTohQAE,00G31000004at3x,ID for SRS Onboarding Queue
Case Round Robin Owner ID,a140Z000005nTorQAE,005i0000001gWx8,Owner ID to trigger Case Round Robin
HG Onboarding Queue,a140Z000005nTowQAE,00Gi00000045vwu,ID for HG Onboarding Queue
Remove From Trending,a140Z000005nVthQAE,kA80Z00000002Z7SAI,Remove From Trending
Opportunity Closed Lost Created Days,a140Z000005kj1CQAQ,5,"If an Account doesn't have an ROE date, the Opp will close lost after this many days"
Jeff Crow,a1431000005Hwa6AAC,a3O31000000DWAz,Major Account Queue for Distribution Groups
Sandy Longman,a1431000005HwZrAAK,a3O31000000DWAp,Major Account Queue for Distribution Groups
Mike Brannelly,a1431000005HwZhAAK,a3O31000000DWAk,Major Account Queue for Distribution Groups
Jared Christensen,a1431000005HwZcAAK,a3O31000000DWBE,Major Account Queue for Distribution Groups
ISR Medical,a1431000005HwZXAA0,a3O31000000DWAa,ISR Medical Queue for Distribution Groups
Amanda Houchins,a1431000005HwaGAAS,a3O31000000DWB9,Major Account Queue for Distribution Groups
ISR General,a1431000005HwZSAA0,a3O31000000DWAV,ISR General Queue for Distribution Groups
Keith Brinkerhoff,a1431000005HwZwAAK,a3O31000000DWAu,Major Account Queue for Distribution Groups
Amber Battaglia,a1431000005HwaBAAS,a3O31000000DWB4,Major Account Queue for Distribution Groups
Current Environment,a1431000005Ia79AAC,Production,Notes Production or Sandbox Environment
Sandbox Contract URL,a1431000005Ia7JAAS,https://full-solutionreachtest.cs52.force.com,Base URL for the contract page in Sandbox
Production Contract URL,a1431000005Ia7EAAS,https://solutionreachtest.secure.force.com,Base URL for the contract page
