({
    doInit : function(component, event, helper) {
    	component.set("v.richtext","<h3><strong>Category</strong></h3><ul><li><p><strong>Bug -&nbsp;</strong>Salesforce isn&rsquo;t doing what it should be doing, or I&rsquo;m getting an error message when trying to do something, etc.</p></li><li><p><strong>Feature Request</strong>&nbsp;- I want to define or automate a process in Salesforce, I need a new field, I need to change a page layout, etc.</p></li><li><p><strong>Access Request</strong>&nbsp;- I can&rsquo;t login, I can&rsquo;t access a record or see/edit a field, new employee, team change, etc.</p></li><li><p><strong>Data Change Request</strong>&nbsp;- My Opportunity didn&rsquo;t go Closed Won, I need to mass update/upload something, the Account ISB Status is incorrect, etc.</p></li><li><p><strong>Reporting Request</strong>&nbsp;- I need a report or a dashboard for regular use, I need to do a one-time report/analysis on specific data, etc.</p></li></ul><h3><strong>Priority Level:</strong></h3><ul><li><p><strong>Level 1 - Critical:</strong></p><ul><li><p>Critical production issue affecting all users and with no workaround.</p></li><li>Desired completion within 1-2 days</li></ul></li><li><p><strong>Level 2 - Urgent:</strong></p><ul><li><p>Major functionality impact or bug affecting multiple users and with no reasonable workaround.</p></li><li>Desired completion within 1 week</li></ul></li><li><p><strong>Level 3 - High:</strong></p><ul><li><p>Minor functionality impact or bug affecting some users.</p></li><li>Can wait for regular prioritization</li></ul></li><li><p><strong>Level 4 - Medium:</strong></p><ul><li><p>Inquiry about routine technical issues, application capabilities, navigation, installation or configuration. Bug affecting a few users.</p></li><li>Nice to have, On the radar</li></ul></li></ul> "); 
    },
    
    handleCategoryChange : function(component, event, helper) {
        var selectedCategory = event.getParam("selectedCategory");
           
    },
})