/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_RecurSoft_Product_SubscriptionTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_RecurSoft_Product_Subscria1DTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new RecurSoft__Product_Subscription__c());
    }
}